apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: multiport-pod
  name: multiport-pod
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  template:
    metadata:
      labels:
        run: multiport-pod
    spec:
      containers:
      - name: multiport-pod
        image: krudisar/multiport-pod
        env:
        - name: ENV_TEST
          value: "just for test"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 22
          protocol: TCP
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
