apiVersion: v1
kind: Service
metadata:
  name: multiport-pod
  namespace: default
  labels:
    run: multiport-pod
spec:
  selector:
    run: multiport-pod
  ports:
  - nodePort:
    name: www 
    protocol: TCP
    port: 80
    targetPort: 80
  - nodePort:
    name: sshd 
    protocol: TCP
    port: 22
    targetPort: 22
  sessionAffinity: None
  type: NodePort

